### ISSUE TITLE
simuPOP is not compatible with python 3.6

### ISSUE THREAD

**Issue by bioinfornatics** [BoPeng/simuPOP#52]
Dear,
Current setup.py declare a dependencies on `distributes` module at [line 745](https://github.com/BoPeng/simuPOP/blob/master/setup.py#L745) . 
Which imply a build failure on python 3.6

````
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
````

> Distribute was a fork of Setuptools. It shared the same namespace, so if you had Distribute installed, import setuptools would actually import the package distributed with Distribute. Distribute was merged back into Setuptools 0.7, so you don't need to use Distribute any more.

Could you replace distribute by setuptools at line 745 please

Thanks

Best regards

**Comment by BoPeng** [comment]
Like this? Please let me know if the patch works for you.

**Comment by bioinfornatics** [comment]
Yes as expected it build fine with python 3.6 now.

Is it possible to use boost as shared library instead to build and link  as static one ?

best regards

**Comment by BoPeng** [comment]
I tried but simuPOP works with some versions, but not others. In the worst case simuPOP could run but crash with unknown reason. It is therefore easiest for me to fix a version of boost that is known to work. Also, boost can be very difficult to install under some systems so it is easier to bundle it so that it can be compiled together with simuPOP.

**Comment by bioinfornatics** [comment]
Thanks for the try.  👍
