### ISSUE TITLE
compile error: simuPOP_shstd not found

### ISSUE THREAD

**Issue by ntakebay** [BoPeng/simuPOP#105]
During the compilation of 1.1.12, I got the following error (gcc version 13.2.1).  The linker can't find simuPOP_shstd.  I couldn't find it in the source and it compiled if I removed -lsimuPOP_shstd.  How can I fix this?

g++ -shared -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -Wl,--build-id=sha1 -g -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -Wl,--build-id=sha1 -g build/temp.linux-x86_64-cpython-311/build/std/genoStru.o build/temp.linux-x86_64-cpython-311/build/std/individual.o build/temp.linux-x86_64-cpython-311/build/std/initializer.o build/temp.linux-x86_64-cpython-311/build/std/mating.o build/temp.linux-x86_64-cpython-311/build/std/migrator.o build/temp.linux-x86_64-cpython-311/build/std/mutator.o build/temp.linux-x86_64-cpython-311/build/std/operator.o build/temp.linux-x86_64-cpython-311/build/std/outputer.o build/temp.linux-x86_64-cpython-311/build/std/pedigree.o build/temp.linux-x86_64-cpython-311/build/std/penetrance.o build/temp.linux-x86_64-cpython-311/build/std/population.o build/temp.linux-x86_64-cpython-311/build/std/qtrait.o build/temp.linux-x86_64-cpython-311/build/std/selector.o build/temp.linux-x86_64-cpython-311/build/std/simulator.o build/temp.linux-x86_64-cpython-311/build/std/stator.o build/temp.linux-x86_64-cpython-311/build/std/tagger.o build/temp.linux-x86_64-cpython-311/build/std/transmitter.o build/temp.linux-x86_64-cpython-311/build/std/utility.o build/temp.linux-x86_64-cpython-311/build/std/virtualSubPop.o build/temp.linux-x86_64-cpython-311/src/simuPOP_std_wrap.o -Lbuild -L/usr/lib64 -lsimuPOP_shstd -lz -lgomp -o build/lib.linux-x86_64-cpython-311/simuPOP/_simuPOP_std.cpython-311-x86_64-linux-gnu.so
/usr/bin/ld: cannot find -lsimuPOP_shstd: No such file or directory
collect2: error: ld returned 1 exit status
error: command '/usr/bin/g++' failed with exit code 1<

**Comment by BoPeng** [comment]
Did you try to compile any other version before?

**Comment by ntakebay** [comment]
Yes, I did compile 1.1.7 when I was using Fedora 35. But I couldn't recompile 1.1.7 with Fedora 38, so I'm trying to compile 1.1.12.  With 1.1.7 and Fedora 38, I think there are problems with math.h of newere glibc when it is compiling gsl.

With 1.1.12, I looked at the compilation log, but there isn't any obvious errors, but it doesn't seem to build the simuPOP-shstd library before the linking.  Which source is the library supposed to be made from?  Previous to the linking, it creates build/temp.linux-x86_64-cpython-311/src/simuPOP_std_wrap.o from simuPOP_std_wrap.cpp.   When I remove "-lsimuPOP_shstd", g++ doesn't complain, and it does create the shared library: _simuPOP_std.cpython-311-x86_64-linux-gnu.so

**Comment by BoPeng** [comment]
`simuPOP_shstd` is a shared library build from boost and other libraries, and will be used to build other modules

https://github.com/BoPeng/simuPOP/blob/50f4776530cd2904196e56927000357da9a564b4/setup.py#L644-L650

If this library failed to build, I suspect it is the boost library that is not supported by the version of gcc you have. Maybe you can change

https://github.com/BoPeng/simuPOP/blob/50f4776530cd2904196e56927000357da9a564b4/setup.py#L99-L101

to a more recent version of boost?

In any case, please let me know the type of os you use, version of gcc, python etc so that i can try to reproduce the problem.

**Comment by ntakebay** [comment]
I'm sorry that was my mistake, and I found out what I was doing wrong.  I was packaging it for RPM, and I was doing "python3 setup.py build", which didn't work.  But if I do "python3 setup.py install", it does finish compiling.  Thank you for your help.

Just for others who are trying to compile on Fedora 38, I should mention that version 1.1.10 and earlier doesn't compile with the following errors (but 1.1.12 compiles ok):

In file included from gsl/sys/infnan.c:21:
/usr/include/bits/mathcalls.h:87:1: error: expected ‘;’ before ‘extern’
   87 | __MATHCALL_VEC (asinh,, (_Mdouble_ __x));
